### ISSUE TITLE
Autores en enmiendas

### ISSUE THREAD

**Issue by joseEnrique** [CIECODE-Madrid/Scrap#16]
Están de otra manera, ej: en la bd esta Ruiz Navarro, Quique y en la enmienda Quique Ruiz Navarro

**Comment by pr3ssh** [comment]
Instala **fuzzywuzzy** y luego simplemente haz el matching así:

```
fuzz.token_sort_ratio("Ruiz Navarro, Quique", "Quique Ruiz Navarro")
```

Ver más [aquí](http://chairnerd.seatgeek.com/fuzzywuzzy-fuzzy-string-matching-in-python/)

**Comment by joseEnrique** [comment]
Se ha implementado con fuzzywuzzy
