### ISSUE TITLE
Cómo tratar las preguntas y respuestas

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/Scrap#22]

**Comment by joseEnrique** [comment]
No está contemplado. ¿Te refieres a las respuestas a las preguntas verdad?. Todo eso se encuentra en los DS, habría que valorarlo y definir hasta cuando responde

**Comment by pr3ssh** [comment]
Hay que valorarlo. Si puedes echarle un ojo y lo que sea preguntarle a @CIECODE pues genial.

**Comment by pr3ssh** [comment]
@joseEnrique hay que pasarlo a tarea no?

**Comment by joseEnrique** [comment]
@pr3ssh si
