### ISSUE TITLE
Buscar enmiendas y guardarlas como otra iniciativa

### ISSUE THREAD

**Issue by joseEnrique** [CIECODE-Madrid/Scrap#3]

**Comment by joseEnrique** [comment]
[link](http://www.congreso.es/portal/page/portal/Congreso/Congreso/Iniciativas/Indice%20de%20Iniciativas?_piref73_1335503_73_1335500_1335500.next_page=/wc/servidorCGI&CMD=VERLST&BASE=IW10&PIECE=IWA0&FMT=INITXD1S.fmt&FORM1=INITXLUS.fmt&DOCS=3-3&QUERY=%28I%29.ACIN1.+%26+%28121%29.SINI.)

Dejo el link de un proyecto de ley. Si vemos los enlaces, hay dos que me producen un poco de duda. El de "Enmiendas del Senado" y el de "Aprobación definitiva". El primero es del congreso y no se donde ubicarlo o si tengo que hacerlo. El segundo será las enmiendas aprobadas no?

**Comment by pr3ssh** [comment]
@joseEnrique De ahí deberíamos coger todo aquello relacionado con el Congreso de los Diputados del BOCG. En este caso, **Enmiendas e índice de enmiendas al articulado** y como está **aprobado con modificaciones** pues **Aprobación definitiva**.

**Comment by joseEnrique** [comment]
@pr3ssh pero enmiedas del senado es del **Congreso de los diputados**. No se si guardarlo como un texto normal o como una enmienda.

**Comment by pr3ssh** [comment]
@joseEnrique las enmiendas del Senado no las guardamos si no me equivoco. Estoy en lo cierto @CIECODE?
