### ISSUE TITLE
Ver el autor de las respuesta

### ISSUE THREAD

**Issue by joseEnrique** [CIECODE-Madrid/Scrap#31]
@pr3ssh de momento coge el de la pregunta. O pongo gobierno directamente, o tengo que hacer match y hacer estadística con todos los miembros y grupos para ver cual se asemeja

**Comment by pr3ssh** [comment]
@joseEnrique Las que sean preguntas al Gobierno se pone como autor Gobierno en la respuesta.

**Comment by joseEnrique** [comment]
@pr3ssh y Pregunta oral en Pleno?

**Comment by pr3ssh** [comment]
@joseEnrique  Diría que en general el autor es el Gobierno, más alla de que hable un ministro u otro. Ponemos por ahora Gobierno y luego testeamos porque la única forma de extraerlo es accediendo al texto crudo de los DS.
