### ISSUE TITLE
Meter en una lista negra las inciativas las rechazadas o  un estado similar

### ISSUE THREAD

**Issue by joseEnrique** [CIECODE-Madrid/Scrap#4]

**Comment by joseEnrique** [comment]
Rechazadas, caducadas,

**Comment by joseEnrique** [comment]
Las iniciativas cuando se aprueban, seguimos escrapeandolas? @pr3ssh

**Comment by pr3ssh** [comment]
@joseEnrique En cualquier caso de aprobación (con o sin modificaciones) se dejan de escrapear ya que no debe de haber novedades.

**Comment by joseEnrique** [comment]
ACK @pr3ssh
