### ISSUE TITLE
Unificar tramitacion y restramitacion

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/Scrap#42]
Para saber qué se usará y dónde tiene que buscar el buscador

**Comment by pr3ssh** [comment]
@joseEnrique dime qué ponemos en el modelo de iniciativas de la app

**Comment by joseEnrique** [comment]
@pr3ssh dejamos tramitacion. Hare un refactor de la inserción y solo metere uno, el campo lo uso en el tratamiento de algunas funciones.

¿El countconten lo dejo? aunque tengo que echarle un vistazo si lo uso mucho

**Comment by pr3ssh** [comment]
@joseEnrique Ok! El *countcontent* a mi no me aporta mucho pero si es un campo de control pues se deja.

**Comment by joseEnrique** [comment]
En la funcion de la iniciativa tengo que unificar el campo del item. Tengo que tocar en el Pipeline y en la conexion a la db. Además countcontent se puede quitar. Tiene pinta que pensé en una accion con ese campo pero que la rechazé

**Comment by pr3ssh** [comment]
@joseEnrique *Go ahead*
