### ISSUE TITLE
El campo contenido de una iniciativa siempre tiene que ser un array de strings

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/Scrap#47]

**Comment by pr3ssh** [comment]
O en tal caso siempre un string de texto pero lo otro puede representar mejor los párrafos o las lineas. @joseEnrique cómo está hecho por ahora?

**Comment by joseEnrique** [comment]
@pr3ssh  ya va en array

**Comment by pr3ssh** [comment]
@joseEnrique Esto en la 121/000008 (Presupuestos generales del estado 2012) de la X legislatura no pasa. Está puesto de forma genérica para todas las iniciativas?
