### ISSUE TITLE
Actualización metadatos si la iniciativa difiere en algo a la información que hay en la bd

### ISSUE THREAD

**Issue by joseEnrique** [CIECODE-Madrid/Scrap#7]

**Comment by joseEnrique** [comment]
Aqui imagino que habrá que consultar primero a la db para saber si se ha modificado algo o no

**Comment by pr3ssh** [comment]
Sí, hay que comprobar los datos de la base de datos para ver si se debe actualizar algo o no. Ahora, creo que el enunciado está mal nO? Debe hacer referencia a que no se debe actualizar nada si la iniciativa ha terminado por alguno de los motivos (creo que ya eso lo habías hecho)

**Comment by joseEnrique** [comment]
Si, estaba mal explicado aunque sabía internamente a que se refería, pero aún así esta corregido
